@echo off
setlocal

set "ROOT=%~dp0"
if "%~1"=="" (
  set "OUT=%ROOT%combined.cpp"
) else (
  set "OUT=%~1"
)

(
  echo // Auto-generated by combine.bat. Do not edit directly.
  echo.
  for %%F in (
    "%ROOT%include\ct_lua54\preamble.hpp"
    "%ROOT%include\ct_lua54\core_types.hpp"
    "%ROOT%include\ct_lua54\lexer_parser.hpp"
    "%ROOT%include\ct_lua54\vm.hpp"
    "%ROOT%include\ct_lua54\modules\base_lib.hpp"
    "%ROOT%include\ct_lua54\modules\table_lib.hpp"
    "%ROOT%include\ct_lua54\modules\math_lib.hpp"
    "%ROOT%include\ct_lua54\modules\string_lib.hpp"
    "%ROOT%include\ct_lua54\modules\api_lib.hpp"
    "%ROOT%include\ct_lua54\demo_main.hpp"
  ) do (
    rem Exclude header-only directive that breaks single-file compile with -Werror.
    findstr /V /C:"#pragma once" "%%~F"
    echo.
  )
) > "%OUT%"

echo Combined file written to "%OUT%"
